# Copyright 2024 Dynatrace LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Bi-weekly build, test and publish Release

on:
#  push:
#    branches:
#      - main
  schedule:
    # At 01:00 on Friday
    #- cron: '0 1 * * 5'
    - cron: '0 * * * *'
  workflow_dispatch:

env:
#  The first run of the action should be scheduled for a date that falls on the same weekday as specified in the cron.
#  For example, if the cron is set to run on Fridays, the first run should be on a Friday.
#  Additionally, during every second week of the bi-weekly cycle, the action will be skipped. The cron time can be set to any time of the day.
#  FIRST_RUN_DATE: 2024-09-06
  FIRST_RUN_DATE: 2024-09-01

jobs:
  biweekly-build-test-and-publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code of the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bi-weekly new tag
        run: |
          currentDate=$(date +%Y-%m-%d)
          start=$(date -d ${{ env.FIRST_RUN_DATE }} +%s)
          end=$(date -d $currentDate +%s)
          #weekDiff=$(((end - start) / 60 / 60 / 24 / 7))
          weekDiff=$(((end - start) / 60 / 60)) #every 1 hour
          weekIndex=$((weekDiff % 2))
          echo "weekIndex = $weekIndex" >> "$GITHUB_STEP_SUMMARY"
          echo "FIRST_RUN_DATE: ${{ env.FIRST_RUN_DATE }}" >> $GITHUB_STEP_SUMMARY
          echo "currentDate: $currentDate" >> $GITHUB_STEP_SUMMARY
          echo "weekDiff: $weekDiff" >> $GITHUB_STEP_SUMMARY
          echo "weekIndex: $weekIndex" >> $GITHUB_STEP_SUMMARY
          if [ $weekIndex -eq 0 ]; then
            echo "Second week -> starting action" >> $GITHUB_STEP_SUMMARY
            git config --global user.email "ci-bot@example.com"
            git config --global user.name "CI Bot"
            currentTagValue=$(git describe --abbrev=0 --tags)
            minor=$(echo $currentTagValue | cut -d '.' -f 2)
            newTagValue=1.$(($minor+1)).0
            git tag -a $newTagValue -m "Bi-weekly tagging with $newTagValue"
            echo "New tag value: $newTagValue" >> $GITHUB_STEP_SUMMARY
            git push origin $newTagValue
          else
            echo "First week -> ignoring action" >> $GITHUB_STEP_SUMMARY
            exit 0
          fi

      - name: Build, test and publish Release
        uses: ./.github/actions/build-test-and-publish-release
        with:
          pat-github-token: ${{ secrets.PAT_GITHUB_TOKEN }}
